### ISSUE TITLE
Can't import spellchecker in electron on macOS

### ISSUE THREAD

**Issue by Septimus** [atom/node-spellchecker#102]
Inside of `webview-preload.js` I am simply trying to import spellchecker before even using it. 

`import { spellchecker } from 'spellchecker'`

```
[11:36:00] 'bundleTask' errored after 3.7 s
[11:36:00] Error:
/app/node_modules/spellchecker/build/Release/spellchecker.node:1
����    ��__TEXTPP      __text__TEXTL�L�__stubs__TEXT('L(�__stub_helper__TEXTt)�t)�__const__TEXT0-��0-__cstring__TEXT�����__gcc_except_tab__TEXTl(l__objc_methname__TEXT�__unwind_info__TEXT���__eh_frame__TEXTX
^
ParseError: Unexpected character '�'
    at formatError (/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
    at Gulp.<anonymous> (/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Object.error (/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/node_modules/once/once.js:25:25)
    at f (/node_modules/once/once.js:25:25)
    at tryCatch (/node_modules/async-done/index.js:24:15)
    at done (node_modules/async-done/index.js:40:12)
```

**Comment by Septimus** [comment]
Issue with browserify. Solved, sorry about this.
