### ISSUE TITLE
Can't install spellchecker@3.5.1

### ISSUE THREAD

**Issue by buffet-time** [atom/node-spellchecker#111]
When trying to install this package for use in an Electron 4.0.7 Application I get the following error:

(i have both python 2.7 and 3.6 installed)

```
C:\Users\daniel\Desktop\electronApp>npm install spellchecker --save

> spellchecker@3.5.1 install C:\Users\daniel\Desktop\electronApp\node_modules\spellchecker
> node-gyp rebuild


C:\Users\daniel\Desktop\electronApp\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:884:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\8.9.4\\node.exe" "C:\\Users\\daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\daniel\Desktop\electronApp\node_modules\spellchecker
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spellchecker@3.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daniel\AppData\Roaming\npm-cache\_logs\2019-03-13T18_39_17_966Z-debug.log

C:\Users\daniel\Desktop\electronApp>
```

anyone have any clue what is the cause? I'm behind a company proxy but not sure if that's the issue.

**Comment by SeanMcP** [comment]
I am having the same issue for `spellcheck@3.5.3`.

**Comment by Berkmann18** [comment]
Same issue here with `spellchecker@3.7.0` + `@types/spellchecker@3.5.0`.

**Comment by StraightOuttaCrompton** [comment]
What version of node are you using? I couldn't install using using ```v13.3.0``` but I could with ```v12.13.1```.

**Comment by zoechi** [comment]
Install failed with Node `v12.16.2`
