### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by asifalikhokhar** [atom/node-spellchecker#38]
I am getting following error when trying to run sudo npm install spellchecker:

> spellchecker@3.2.3 install /Users/asifali/Documents/Apps/SlickNotes/node_modules/spellchecker
> node-gyp rebuild

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/asifali/Documents/Apps/SlickNotes/node_modules/spellchecker
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "spellchecker" "--save"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
**

> npm ERR! Failed at the spellchecker@3.2.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the spellchecker package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild

**
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

**Comment by asifalikhokhar** [comment]
It was Xcode's issue, xcode was updated and was not opened since then.
