### ISSUE TITLE
Latest version cannot be installed

### ISSUE THREAD

**Issue by ChrisJefferson** [atom/node-spellchecker#39]
Version spellchecker@3.2.3 will not install under atom beta, when `spell-check-test` tries to update itself inside Atom. The following error occurs. The package installs fine using `apm install spell-check-test`. I would guess the problem is that there is a space in `Atom Beta.app`?

```
> spellchecker@3.2.3 install /private/var/folders/hh/197lrmmn40g6hhnqfxf1jp5h0000gn/T/apm-install-dir-116214-16178-6u5uaq/node_modules/spell-check-test/node_modules/spellchecker
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/hh/197lrmmn40g6hhnqfxf1jp5h0000gn/T/apm-install-dir-116214-16178-6u5uaq/node_modules/spell-check-test/node_modules/spellchecker
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/caj/.atom/.apm/.apmrc" "--userconfig" "/Users/caj/.atom/.apmrc" "install" "/private/var/folders/hh/197lrmmn40g6hhnqfxf1jp5h0000gn/T/d-116214-16178-pz2va0/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/hh/197lrmmn40g6hhnqfxf1jp5h0000gn/T/apm-install-dir-116214-16178-6u5uaq/npm-debug.log
```

**Comment by abnerlee** [comment]
Same on 3.3.1

```
export npm_config_disturl=https://atom.io/download/atom-shell ; export npm_config_target=1.0.2 ; export npm_config_arch=x64;  export npm_config_runtime=electron ; HOME=~/.electron-gyp npm install spellchecker --global-style
```


```
> node-gyp rebuild

  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o
../vendor/hunspell/src/hunspell/affentry.cxx:544:47: warning: while loop has
      empty body [-Wempty-body]
                        while (p && *p != ']' && (p = nextchar(p)));
                                                                   ^
../vendor/hunspell/src/hunspell/affentry.cxx:544:47: note: put the semicolon on
      a separate line to silence this warning
1 warning generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affixmgr.o
In file included from ../vendor/hunspell/src/hunspell/affixmgr.cxx:12:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: implicit
      conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  ...char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                 ~ ^~~~
                                                                   0
../vendor/hunspell/src/hunspell/affentry.hxx:93:114: warning: implicit
      conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  ...int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                ~ ^~~~
                                                                  0
../vendor/hunspell/src/hunspell/affixmgr.cxx:3654:65: warning: 'strncmp' call
      operates on objects of type 'const char' while the size is based on a
      different type 'const char *' [-Wsizeof-pointer-memaccess]
  ...if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                        ~~~~~~~         ^~~~~~~
../vendor/hunspell/src/hunspell/affixmgr.cxx:3654:65: note: did you mean to
      provide an explicit length?
  ...if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                        ^~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/dictmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hashmgr.o
In file included from ../vendor/hunspell/src/hunspell/hashmgr.cxx:9:
../vendor/hunspell/src/hunspell/hashmgr.hxx:17:21: warning: private field
      'userword' is not used [-Wunused-private-field]
  int               userword;
                    ^
1 warning generated.
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunspell.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/suggestmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/parsers/textparser.o
  LIBTOOL-STATIC Release/hunspell.a
  CXX(target) Release/obj.target/spellchecker/src/main.o
In file included from ../src/main.cc:2:
../../nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/spellchecker/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/abner/workplace/HybirdApp/TypeMark/node_modules/spellchecker
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "spellchecker" "--global-style"
npm ERR! node v0.12.3
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abner/workplace/HybirdApp/TypeMark/npm-debug.log
```
