### ISSUE TITLE
Errors while installing it on Windows 10

### ISSUE THREAD

**Issue by lipis** [atom/node-spellchecker#62]
Am I doing something wrong? Any clue?

```
C:\Users\Lipis\my-app [spell ≡]> npm install spellchecker

> spellchecker@3.3.1 install C:\Users\Lipis\my-app\node_modules\spellchecker
> node-gyp rebuild


C:\Users\Lipis\my-app\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\Lipis\my-app\node_modules\spellchecker\build\..\vendor\hunspell\src\hunspell\utf_info.hxx
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  affentry.cxx
  affixmgr.cxx
  csutil.cxx
  dictmgr.cxx
  filemgr.cxx
  hashmgr.cxx
  hunspell.cxx
  hunzip.cxx
  phonet.cxx
  replist.cxx
  suggestmgr.cxx
  textparser.cxx
  win_delay_load_hook.cc
  hunspell.vcxproj -> C:\Users\Lipis\my-app\node_modules\spellch
  ecker\build\Release\\hunspell.lib
  main.cc
  spellchecker_hunspell.cc
  spellchecker_win.cc
  transcoder_win.cc
  win_delay_load_hook.cc
C:\Users\Lipis\.node-gyp\6.9.1\Release\node.lib : fatal error LNK1106: invalid file or disk full
: cannot seek to 0x645B0 [C:\Users\Lipis\my-app\node_modules\spe
llchecker\build\spellchecker.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Lipis\my-app\node_modules\spellchecker
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "spellchecker"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lipis\my-app\npm-debug.log
```

**Comment by ilya-fedin** [comment]
```

> ghetto-skype@ postinstall C:\Users\Илья\ghetto-skype-develop
> install-app-deps

Installing app dependencies for arch ia32 to C:\Users\Илья\ghetto-skype-develop\src
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> @paulcbetts/spellchecker@4.0.4 install C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker
> node-gyp rebuild


C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Warning: Missing input files:
C:\Users\����\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\..\vendor\hunspell\src\build\build.h
Построение проектов в этом решении по одному. Чтобы включить параллельное построение, добавьте параметр "/m".
  md5.cc
  string_piece.cc
  bdict_reader.cc
  bdict.cc
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
  affentry.cxx
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
  affixmgr.cxx
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
..\vendor\hunspell\src\base\strings\string_piece.cc(40): error C2960: base::BasicStringPiece<STRING_TYPE>: несогласованное явное создание экземпляров, в предыдущем явном создании экземпляров указано "extern template" [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
          with
          [
              STRING_TYPE=std::string
          ]
..\vendor\hunspell\src\base\strings\string_piece.cc(41): error C2960: base::BasicStringPiece<STRING_TYPE>: несогласованное явное создание экземпляров, в предыдущем явном создании экземпляров указано "extern template" [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
          with
          [
              STRING_TYPE=base::string16
          ]
  csutil.cxx
  dictmgr.cxx
  filemgr.cxx
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
  hashmgr.cxx
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
  hunspell.cxx
  hunzip.cxx
  phonet.cxx
  replist.cxx
  suggestmgr.cxx
  textparser.cxx
  win_delay_load_hook.cc
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(372): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]
C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\vendor\hunspell\src\base/strings/string_piece.h(373): warning C4231: нестандартное расширение: "extern" перед явным созданием экземпляра шаблона [C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker\build\hunspell.vcxproj]

Error output:
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Илья\ghetto-skype-develop\src\node_modules\@paulcbetts\spellchecker
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN ghetto-skype@1.5.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! @paulcbetts/spellchecker@4.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @paulcbetts/spellchecker@4.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @paulcbetts/spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @paulcbetts/spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @paulcbetts/spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Илья\ghetto-skype-develop\src\npm-debug.log

    at ChildProcess.childProcess.once.code (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\src\util\util.ts:136:14)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\src\util\util.ts:99:3)
    at installDependencies (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\src\yarn.ts:56:3)
    at C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\src\yarn.ts:12:11
    at Generator.next (<anonymous>)
From previous event:
    at installOrRebuild (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\src\cli\install-app-deps.ts:34:2
    at Generator.next (<anonymous>)
From previous event:
    at main (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\out\cli\install-app-deps.js:36:21)
    at Object.<anonymous> (C:\Users\Илья\ghetto-skype-develop\node_modules\electron-builder\out\cli\install-app-deps.js:76:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ghetto-skype@ postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR! 
npm ERR! Failed at the ghetto-skype@ postinstall script 'install-app-deps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghetto-skype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghetto-skype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghetto-skype
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Илья\ghetto-skype-develop\npm-debug.log

```
I have a similar error (Visual Studio 2010)
PS: Sorry for Russian in a log, I don't know how to make it in English on Windows, my main system is Linux and simple LANG=C works on it :(

**Comment by tikhonandrey** [comment]
hi, 
try this 
`npm install --global --production windows-build-tools`
https://github.com/nodejs/node-gyp#installation

**Comment by divgit** [comment]
My solution on Windows 10. 
Only these solution helps.
You need file **visualcppbuildtools_full.exe** !!
Go here https://visualstudio.microsoft.com/ru/visual-cpp-build-tools/
My link: https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe
You require file: visualcppbuildtools_full.exe.
Install all versions for windows 8.1 and 10 (~6-8Gb).
Its create folder C:\Program Files (x86)\MSBuild\**Microsoft.Cpp\v4.0\v140...**
And be happy :-)
